FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 5044

ENV ASPNETCORE_URLS=http://+:5044

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Copy solution and project files first
COPY ["Discoteque.sln", "."]
COPY ["Discoteque.API/Discoteque.API.csproj", "Discoteque.API/"]
COPY ["Discoteque.Business/Discoteque.Business.csproj", "Discoteque.Business/"]
COPY ["Discoteque.Data/Discoteque.Data.csproj", "Discoteque.Data/"]
COPY ["Discoteque.Tests/Discoteque.Tests.csproj", "Discoteque.Tests/"]

# Restore NuGet packages
RUN dotnet restore

# Copy the rest of the source code
COPY . .

# Install EF Core tools
RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"

# Build the application
WORKDIR "/src/Discoteque.API"
RUN dotnet build "Discoteque.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Discoteque.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

ENTRYPOINT ["dotnet", "Discoteque.API.dll"]